[package]
name = "sentience"
version = "0.1.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
atty = "0.2"
tracing = "0.1"

[lib]
name = "sentience"
path = "src/lib.rs"

[[bin]]
name = "sentience-repl"
path = "src/main.rs"
